version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: myLog-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  
  nginx:
    image: nginx:1.19-alpine
    container_name: myLog_nginx
    restart: always
    ports:
      - 500:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
